# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 06:27


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cours_complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Info_membres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_membre', models.IntegerField(unique=True)),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('photo', models.ImageField(height_field=300, upload_to=b'', width_field=300)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('courriel', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('nombre_enfants', models.IntegerField(default=0)),
                ('etat_civil', models.CharField(max_length=50)),
                ('prenom_conjoint', models.CharField(max_length=50)),
                ('nom_conjoint', models.CharField(max_length=50)),
                ('information_sur_eglise_precedente', models.CharField(max_length=200)),
                ('a_suivi_cours_la_foi_transforme', models.BooleanField(default=False)),
                ('a_suivi_cours_de_predication', models.BooleanField(default=False)),
                ('a_suivi_cours_de_membre', models.BooleanField(default=False)),
                ('a_suivi_cours_de_ouvrier', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='info_suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suivi_detail', models.CharField(max_length=150)),
                ('date', models.DateTimeField(verbose_name='date de modification')),
            ],
        ),
        migrations.CreateModel(
            name='ref_liste_de_cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ref_Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('poste', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ref_Statut_membre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ref_type_de_suivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ref_type_de_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='transaction_financiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_Staff')),
                ('numero_de_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.Info_membres')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_type_de_transaction')),
            ],
        ),
        migrations.AddField(
            model_name='info_suivi',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_Staff'),
        ),
        migrations.AddField(
            model_name='info_suivi',
            name='numero_de_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.Info_membres'),
        ),
        migrations.AddField(
            model_name='info_membres',
            name='statut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_Statut_membre'),
        ),
        migrations.AddField(
            model_name='cours_complete',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_liste_de_cours'),
        ),
        migrations.AddField(
            model_name='cours_complete',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.ref_Staff'),
        ),
        migrations.AddField(
            model_name='cours_complete',
            name='numero_de_membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtapp.Info_membres'),
        ),
    ]
