# Generated by Django 2.1 on 2018-08-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtapp', '0003_transaction_financiere_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours_complete',
            name='modified_by',
            field=models.ForeignKey(on_delete=None, to='vtapp.ref_Staff'),
        ),
        migrations.AlterField(
            model_name='info_membres',
            name='statut',
            field=models.ForeignKey(on_delete=None, to='vtapp.ref_Statut_membre'),
        ),
        migrations.AlterField(
            model_name='info_suivi',
            name='modified_by',
            field=models.ForeignKey(on_delete=None, to='vtapp.ref_Staff'),
        ),
        migrations.AlterField(
            model_name='transaction_financiere',
            name='modified_by',
            field=models.ForeignKey(on_delete=None, to='vtapp.ref_Staff'),
        ),
        migrations.AlterField(
            model_name='transaction_financiere',
            name='transaction',
            field=models.ForeignKey(on_delete=None, to='vtapp.ref_type_de_transaction'),
        ),
    ]
